name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: pamp_project_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Copy example .env file
        run: |
          cat > .env << EOL
          DATABASE_URL=postgres://postgres:postgres@localhost:5432/pamp_project_test
          DATABASE_HOST=localhost
          DATABASE_PORT=5432
          DATABASE_USERNAME=postgres
          DATABASE_PASSWORD=postgres
          DATABASE_NAME=pamp_project_test
          JWT_SECRET=test_secret_for_ci
          JWT_EXPIRATION=3600
          EOL

      - name: Run tests
        run: npm test 